SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `league_members` 
ADD COLUMN `LeagueMemberID` INT(15) UNSIGNED NOT NULL FIRST,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`LeagueMemberID`),
ADD UNIQUE INDEX `UQ1_LEAGUE_MEMBERS` (`LeagueID` ASC, `TeamID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;